from controllers.mqtt import *
from controllers.ws import *
from controllers.machines import *
from controllers.temperature import *
from controllers.humidity import *
from controllers.user import *
from controllers.switch import *
from controllers.sensors import *
from controllers.section import *
from controllers.watersupply import *
from controllers.spraytime import *
from controllers.sprayterm import *
from controllers.nutrientsupply import *
from controllers.report import *
from controllers.auth import *
from controllers.automation import *
